-- The whole schema, for pasting into a SQL console.
--
-- Generated by scripts/build-schema-sql.mjs from the drizzle migrations.
-- Do not hand-edit; run `npm run db:schema` after changing db/schema.ts,
-- so this file and the migrations cannot quietly disagree.
--
-- Run against an empty database, in this order. To start over on one that
-- already has these tables, run docs/reset.sql first — it drops them all.
-- To see what a database currently has:
--   select name from sqlite_master where type = 'table';
--
-- Ordinary schema changes still go through drizzle:
--   npm run db:generate   (write a migration)
--   npm run db:migrate    (apply it)
-- This file is the way in when the driver cannot reach the database at
-- all, and the last two statements are what keep those two worlds
-- agreeing.

CREATE TABLE `accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`group` text NOT NULL,
	`name` text NOT NULL,
	`currency` text DEFAULT 'KRW' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`active_from` text,
	`active_to` text,
	`memo` text,
	`category` text,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "accounts_group_check" CHECK("accounts"."group" IN ('asset','liability','equity','expense','income')),
	CONSTRAINT "accounts_active_from_format_check" CHECK("accounts"."active_from" IS NULL OR "accounts"."active_from" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "accounts_active_to_format_check" CHECK("accounts"."active_to" IS NULL OR "accounts"."active_to" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
	CONSTRAINT "accounts_active_range_check" CHECK("accounts"."active_from" IS NULL OR "accounts"."active_to" IS NULL OR "accounts"."active_from" <= "accounts"."active_to")
);

CREATE INDEX `accounts_section_group_idx` ON `accounts` (`section_id`,`group`);

CREATE UNIQUE INDEX `accounts_section_name_unique` ON `accounts` (`section_id`,`name`);

CREATE TABLE `auth_account` (
	`user_id` text NOT NULL,
	`type` text NOT NULL,
	`provider` text NOT NULL,
	`provider_account_id` text NOT NULL,
	`refresh_token` text,
	`access_token` text,
	`expires_at` integer,
	`token_type` text,
	`scope` text,
	`id_token` text,
	`session_state` text,
	PRIMARY KEY(`provider`, `provider_account_id`),
	FOREIGN KEY (`user_id`) REFERENCES `auth_user`(`id`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE `auth_session` (
	`session_token` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`expires` integer NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `auth_user`(`id`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE `auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text,
	`email` text,
	`email_verified` integer,
	`image` text
);

CREATE UNIQUE INDEX `auth_user_email_unique` ON `auth_user` (`email`);

CREATE TABLE `auth_verification_token` (
	`identifier` text NOT NULL,
	`token` text NOT NULL,
	`expires` integer NOT NULL,
	PRIMARY KEY(`identifier`, `token`)
);

CREATE TABLE `budgets` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`account_id` text NOT NULL,
	`year_month` text NOT NULL,
	`amount` integer NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "budgets_year_month_format_check" CHECK("budgets"."year_month" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]')
);

CREATE UNIQUE INDEX `budgets_account_year_month_unique` ON `budgets` (`account_id`,`year_month`);

CREATE TABLE `exchange_rates` (
	`date` text NOT NULL,
	`base` text NOT NULL,
	`quote` text NOT NULL,
	`rate` real NOT NULL,
	`source` text NOT NULL,
	PRIMARY KEY(`date`, `base`, `quote`),
	CONSTRAINT "exchange_rates_source_check" CHECK("exchange_rates"."source" IN ('api','manual')),
	CONSTRAINT "exchange_rates_date_format_check" CHECK("exchange_rates"."date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
);

CREATE TABLE `sections` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`base_currency` text DEFAULT 'KRW' NOT NULL,
	`timezone` text DEFAULT 'Asia/Seoul' NOT NULL,
	`start_date` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`nav_favorites` text DEFAULT '/,/assets,/income,/budget' NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `auth_user`(`id`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE `transaction_lines` (
	`id` text PRIMARY KEY NOT NULL,
	`transaction_id` text NOT NULL,
	`line_order` integer DEFAULT 0 NOT NULL,
	`side` text NOT NULL,
	`account_id` text NOT NULL,
	`currency` text NOT NULL,
	`amount` integer NOT NULL,
	`rate` real,
	`base_amount` integer NOT NULL,
	`memo` text,
	FOREIGN KEY (`transaction_id`) REFERENCES `transactions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE restrict,
	CONSTRAINT "transaction_lines_side_check" CHECK("transaction_lines"."side" IN ('left','right')),
	CONSTRAINT "transaction_lines_amount_check" CHECK("transaction_lines"."amount" >= 0),
	CONSTRAINT "transaction_lines_base_amount_check" CHECK("transaction_lines"."base_amount" >= 0)
);

CREATE INDEX `transaction_lines_transaction_idx` ON `transaction_lines` (`transaction_id`);

CREATE INDEX `transaction_lines_account_idx` ON `transaction_lines` (`account_id`);

CREATE TABLE `transactions` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`date` text NOT NULL,
	`title` text NOT NULL,
	`memo` text,
	`kind` text DEFAULT 'normal' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "transactions_kind_check" CHECK("transactions"."kind" IN ('normal','opening','revaluation')),
	CONSTRAINT "transactions_date_format_check" CHECK("transactions"."date" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
);

CREATE INDEX `transactions_section_date_idx` ON `transactions` (`section_id`,`date`);

ALTER TABLE `sections` ADD `group_order` text DEFAULT 'asset,liability,equity,expense,income' NOT NULL;

-- Hand-corrected over what `drizzle-kit` generated. Its rebuild selected
-- the new columns out of the old table (which cannot work) and wrapped
-- itself in `PRAGMA foreign_keys`, which a remote libSQL server refuses.
--
-- The PRAGMA is not needed here at all: `budgets` references other
-- tables but nothing references *it*, so dropping and recreating it
-- never trips a foreign key. The existing rows carry across as month
-- budgets, which is what every one of them was.

CREATE TABLE `__new_budgets` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`account_id` text NOT NULL,
	`year_month` text DEFAULT '' NOT NULL,
	`period` text DEFAULT 'month' NOT NULL,
	`period_key` text NOT NULL,
	`amount` integer NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "budgets_period_check" CHECK("__new_budgets"."period" IN ('month','year')),
	CONSTRAINT "budgets_period_key_format_check" CHECK(("__new_budgets"."period" = 'month' AND "__new_budgets"."period_key" GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]')
       OR ("__new_budgets"."period" = 'year' AND "__new_budgets"."period_key" GLOB '[0-9][0-9][0-9][0-9]'))
);

INSERT INTO `__new_budgets`("id", "section_id", "account_id", "year_month", "period", "period_key", "amount") SELECT "id", "section_id", "account_id", "year_month", 'month', "year_month", "amount" FROM `budgets`;

DROP TABLE `budgets`;

ALTER TABLE `__new_budgets` RENAME TO `budgets`;

CREATE UNIQUE INDEX `budgets_account_year_month_unique` ON `budgets` (`account_id`,`year_month`);

CREATE UNIQUE INDEX `budgets_account_period_unique` ON `budgets` (`account_id`,`period`,`period_key`);

DROP INDEX `budgets_account_year_month_unique`;

ALTER TABLE `budgets` DROP COLUMN `year_month`;

ALTER TABLE `accounts` ADD `tracks_counterparties` integer DEFAULT false NOT NULL;

CREATE TABLE `formulas` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`scope` text NOT NULL,
	`name` text NOT NULL,
	`terms` text DEFAULT '[]' NOT NULL,
	`expression` text DEFAULT '' NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "formulas_scope_check" CHECK("formulas"."scope" IN ('assets','income'))
);

CREATE INDEX `formulas_section_scope_idx` ON `formulas` (`section_id`,`scope`,`sort_order`);

CREATE TABLE `roadmaps` (
	`id` text PRIMARY KEY NOT NULL,
	`section_id` text NOT NULL,
	`name` text NOT NULL,
	`start_year` text NOT NULL,
	`end_year` text NOT NULL,
	`starting_amount` integer DEFAULT 0 NOT NULL,
	`default_contribution` integer DEFAULT 0 NOT NULL,
	`default_return_rate` real DEFAULT 0 NOT NULL,
	`actual_formula_id` text,
	`sort_order` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`section_id`) REFERENCES `sections`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`actual_formula_id`) REFERENCES `formulas`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "roadmaps_start_year_format_check" CHECK("roadmaps"."start_year" GLOB '[0-9][0-9][0-9][0-9]'),
	CONSTRAINT "roadmaps_end_year_format_check" CHECK("roadmaps"."end_year" GLOB '[0-9][0-9][0-9][0-9]')
);

CREATE INDEX `roadmaps_section_idx` ON `roadmaps` (`section_id`,`sort_order`);

CREATE TABLE `roadmap_years` (
	`id` text PRIMARY KEY NOT NULL,
	`roadmap_id` text NOT NULL,
	`year` text NOT NULL,
	`contribution` integer,
	`return_rate` real,
	`note` text,
	FOREIGN KEY (`roadmap_id`) REFERENCES `roadmaps`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "roadmap_years_year_format_check" CHECK("roadmap_years"."year" GLOB '[0-9][0-9][0-9][0-9]')
);

CREATE UNIQUE INDEX `roadmap_years_year_unique` ON `roadmap_years` (`roadmap_id`,`year`);

ALTER TABLE `roadmaps` ADD `actual_source` text DEFAULT 'none' NOT NULL;

UPDATE `roadmaps` SET `actual_source` = 'formula' WHERE `actual_formula_id` IS NOT NULL;

-- Drizzle's bookkeeping. The app never reads it; `drizzle-kit migrate`
-- does, to know what has already run. Recording the migrations this file
-- is equivalent to is what stops the next `npm run db:migrate` from
-- starting at 0000 and failing on tables that are already here.

CREATE TABLE `__drizzle_migrations` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`hash` text NOT NULL,
	`created_at` numeric
);

INSERT INTO `__drizzle_migrations` (`hash`, `created_at`) VALUES
	('e080edf6f58176c92afda1a1b598c7fe643504fe3557927e846a40f2f54c8879', 1785906516337),
	('1cf9aeeb26a3a693893dfa2178d42c2788adfbbb31d14c78e42c31217ab5cdb8', 1785991646983),
	('bcce57e61f7b16e016296bdb38cc65366ac41fd58e8f03e915164881e450b9ec', 1786247084505),
	('90af2c3f8c0a8855ca94b67b6a24c69797eda38faf44e28bc9833ca76502ede5', 1786247135287),
	('432d2627f2a56171a64b61882fb7ddf9123dfe01c8025dc31bf4351ceb46300d', 1786250222679),
	('ae1ee42ebfb7fd5da657e298e98145c70a23156e62bab7543d48512d0191fddf', 1786284806351),
	('eb3ec6da0c002299c0c5a8a38560b242d29f58625708682d04f87bcc2e4362a3', 1787034469652),
	('3dead2f383918ab4fd1338d994f27509f5d589467becfea29e4bda111afbd3dd', 1787207533286);
